### ISSUE TITLE
Android org.json.JSONException

### ISSUE THREAD

**Issue by yleflour** [convertigo/react-native-c8osdk#8]
In 1.0.5-beta13

A `exception  D  org.json.JSONException: No value for __localCache` is triggered upon requests

**Comment by CharlesGrimont** [comment]
In java Android, to get the value object associated with a key into a jsonObject, we must use the [get method](https://processing.github.io/processing-javadocs/core/processing/data/JSONObject.html#get-java.lang.String-), which throw an exception when the key do not exists in the current JsonObject.

This is just the trace that show us that we haven't found any localcache parameters for this request...

In no cases this represent a bug

As this log can be very confusing, if you need it we can remove the log from the next versions

[See the code](https://github.com/convertigo/react-native-c8osdk/blob/master/android/src/main/java/com/convertigo/reactnative/RCTC8oSDK.java#L118-L132)
